export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

export const SET_ARTISTS = 'SET_ARTISTS';
export const REMOVE_ARTISTS = 'REMOVE_ARTISTS';

export const SET_LAST_SEARCH = 'SET_LAST_SEARCH';

export const SET_CURRENT_ARTIST = 'SET_CURRENT_ARTIST';
export const REMOVE_CURRENT_ARTIST = 'REMOVE_CURRENT_ARTIST';

export const SET_ALBUMS = 'SET_ALBUMS';
export const REMOVE_ALBUMS = 'REMOVE_ALBUMS';

export const SET_NEXT_ARTISTS_URL = 'SET_NEXT_ARTISTS_URL';
export const SET_NEXT_ALBUMS_URL = 'SET_NEXT_ALBUMS_URL';
